name: 'Terraform Apply'

on:
  push:
    branches: [master]
    paths:
      - 'repos/**'

env:
  AWS_AK: XXXXXXXXXXXXXXXXX
  AWS_SAK: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  GH_TKN: ${{ secrets.ORG_GH_TKN }}

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v2
    #     with:
    #       aws-access-key-id: ${ env.AWS_AK }
    #       aws-secret-access-key: ${ env.AWS_SAK }
    #       aws-region: us-east-1

      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Create Additional Branches
        run: |
          find repos -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | xargs -I {} ./scripts/setup-branches.sh {}
    
      - name: Set Environment Secrets
        run: |
          sudo apt-get install -y jq
          find repos -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read repo; do
            for env in dev test prod; do
            echo "Setting secrets for $repo environment $env"
            gh api -X PUT "repos/tu-organizacion/$repo/environments/$env/secrets/AWS_AK" \
                -f encrypted_value="$(echo -n "$AWS_AK" | base64)"
            gh api -X PUT "repos/tu-organizacion/$repo/environments/$env/secrets/AWS_SAK" \
                -f encrypted_value="$(echo -n "$AWS_SAK" | base64)"
            done
          done